apiVersion: v1
kind: Service
metadata:
  name: movies-service
spec:
  selector:
    app: movies
  ports:
    - port: 80
      targetPort: 5000    # Targetport na 5000 porque é onde o container está rodando
  type: LoadBalancer    # LoadBalancer para rodar na nuvem
